swagger: "2.0"
info:
  title: hwp-manager
  description: hwp-manager test
  version: 0.0.1
#host: localhost:3002
schemes:
  - http
  - https

tags:
  - name: work
    description: 문제 처리 포맷입니다.

securityDefinitions:
  jwt:
    type: "basic"

  bearer:
    type: apiKey
    name: Authorization
    in: header

security:
  - jwt: []
  - bearer: []

paths:
  /question/hwpMetadataExtract:
    post:
      summary: "hwp 파일의 metadata를 추출합니다."
      description: "workGroupId : metadata를 분석할 파일들의 S3 Key의 prefix입니다.\ncallbackUrl : taskKey를 return할 주소입니다.\nAWS SNS에 아래와 같은 형태로 callback됩니다.\n
      \t{\n
        \t\tsecretKey: string,
        \t\tmetadatas: {
          \t\t\tEdgeDetect: {
            \t\t\t\theight: integer,
            \t\t\t\tthumbnail: string}
          \t\t\t},
          \t\t\tTextConvert: string
        \t\t}
      \t}\n"

      tags:
        - work
      parameters:
        - name: body
          in: body
          required: true
          schema:
            properties:
              workGroupId:
                type: string
              callbackUrl:
                type: string
              dynamicContents:
                type: object
                properties:
                  data:
                    type: string

      responses:
        200:
          description: "taskKey와 S3에 업로드된 문제의 key를 내려줍니다."
          schema:
            properties:
              taskKey:
                type: string
        400:
          description: "Bad Request : 요청이 잘못되었습니다."
        404:
          description: "Not Found : S3에 파일이 없습니다."
        500:
          description: "Unexpected Exception : 알 수 없는 에러입니다."

  /question/questionSplit:
    post:
      summary: "hwp 파일의 문제들을 split합니다."
      description: "questionFileKey: 나눌 문제 파일의 Key입니다.\answerFileKey: 나눌 정답 파일의 Key입니다.\ncallbackUrl: 결과를 return할 주소입니다."
      tags:
        - work
      parameters:
        - name: body
          in: body
          required: true
          schema:
            properties:
              questionFileKey:
                type: string
              answerFileKey:
                type: string
              callbackUrl:
                type: string

      responses:
        200:
          description: "split하여 업로드된 파일들의 Key의 prefix를 내려줍니다."
          schema:
            properties:
              workGroupId:
                type: string
        400:
          description: "Bad Request : 요청이 잘못되었습니다."
        404:
          description: "Not Found : S3에 파일이 없습니다."
        500:
          description: "Unexpected Exception : 알 수 없는 에러입니다."

  /question/makePaper:
    post:
      summary: "문제 list를 시험지로 만듭니다."
      description: "questionFileKeys: string[] \n"
      tags:
        - work
      parameters:
        - name: body
          in: body
          required: true
          schema:
            properties:
              questionFileKey:
                type: string
              answerFileKey:
                type: string
              callbackUrl:
                type: string

      responses:
        200:
          description: "생성된 시험지의 Key를 내려줍니다."
          schema:
            properties:
              paperKey:
                type: string
        400:
          description: "Bad Request : 요청이 잘못되었습니다."
        404:
          description: "Not Found : S3에 파일이 없습니다."
        500:
          description: "Unexpected Exception : 알 수 없는 에러입니다."