swagger: "2.0"
info:
  title: hwp-manager
  description: hwp-manager test
  version: 0.0.1
#host: localhost:3002
schemes:
  - http
  - https

tags:
  - name: work
    description: 문제 처리 포맷입니다.

securityDefinitions:
  jwt:
    type: "basic"

  bearer:
    type: apiKey
    name: Authorization
    in: header

security:
  - jwt: []
  - bearer: []

paths:
  /question/hwpMetadataExtract:
    post:
      summary: "hwp 파일의 metadata를 추출합니다."
      description: "workGroupId : metadata를 분석할 파일들의 S3 Key의 prefix입니다.\ncallbackUrl : taskKey를 return할 주소입니다.\nAWS SNS에 아래와 같은 형태로 callback됩니다.\n
      ```typescript
      message : {
        \tdata : Result
        \tworkKey : string
      }
      ```
      ```typescript
      Result : {
        \tquestionKey : string
        \tanswerKey : string
        \tmetadata : Metadata

        \tquestionGroupKey? : string
        \twc? : WC
      }
      ```
      ```typescript
      Metadata : {
        \tlevel: string | null
        \tpublisher: string | null
        \ttag: string | null
        \tcategory: string | null
        \ttype: string | null
        \tquestionFileMetadata: FileMetadata
        \tanswerFileMetadata: FileMetadata
      }
      ```
      ```typescript
      WC : {
        \tquestionKey: string
        \tquestionFileMetadata: FileMetadata
      }
      ```
      ```typescript
      FileMetadata : {
        imageHeight: number
        thumbnailKey: string
        extractedImageKey: string
        text: string
      }
      ```
      "

      tags:
        - work
      parameters:
        - name: body
          in: body
          required: true
          schema:
            properties:
              workGroupId:
                type: string

      responses:
        200:
          description: "taskKey와 S3에 업로드된 문제의 key를 내려줍니다."
          schema:
            properties:
              taskKey:
                type: string
        400:
          description: "Bad Request : 요청이 잘못되었습니다."
        404:
          description: "Not Found : S3에 파일이 없습니다."
        500:
          description: "Unexpected Exception : 알 수 없는 에러입니다."

  /question/questionSplit:
    post:
      summary: "hwp 파일의 문제들을 split합니다."
      description: "questionFileKey: 나눌 문제 파일의 Key입니다.\nanswerFileKey: 나눌 정답 파일의 Key입니다.\ncallbackUrl: 결과를 return할 주소입니다."
      tags:
        - work
      parameters:
        - name: body
          in: body
          required: true
          schema:
            properties:
              questionFileKey:
                type: string
              answerFileKey:
                type: string
              callbackUrl:
                type: string

      responses:
        200:
          description: "split하여 업로드된 파일들의 Key의 prefix를 내려줍니다."
          schema:
            properties:
              workGroupId:
                type: string
        400:
          description: "Bad Request : 요청이 잘못되었습니다."
        404:
          description: "Not Found : S3에 파일이 없습니다."
        500:
          description: "Unexpected Exception : 알 수 없는 에러입니다."

  /question/makePaper:
    post:
      summary: "문제 list를 시험지로 만듭니다."
      description: "questionFileKeys: 시험지로 만들 문제들의 Key의 list입니다.\ndynamicContents: 표지에 들어갈 내용입니다. data: 한글 누름틀 이름, string: 내용 입니다.\n"
      tags:
        - work
      parameters:
        - name: body
          in: body
          required: true
          schema:
            properties:
              questionFileKeys:
                type: array
                item:
                  type: string
              dynamicContents:
                type: object
                properties:
                  data:
                    type: string

      responses:
        200:
          description: "생성된 시험지의 Key를 내려줍니다."
          schema:
            properties:
              paperKey:
                type: string
        400:
          description: "Bad Request : 요청이 잘못되었습니다."
        404:
          description: "Not Found : S3에 파일이 없습니다."
        500:
          description: "Unexpected Exception : 알 수 없는 에러입니다."