swagger: "2.0"
info:
  title: dog-manager
  description: dog-manager test
  version: 0.0.1
#host: localhost:3002
schemes:
  - http
  - https

tags:
  - name: dog
    description: 반려견 소리 처리 포맷입니다.

securityDefinitions:
  jwt:
    type: "basic"

  bearer:
    type: apiKey
    name: Authorization
    in: header

security:
  - jwt: []
  - bearer: []

paths:
  /test:
    get:
      summary: "연결 상태 테스트"
      description: "테스트"
      tags:
        - dog

      responses:
        200:
          description: "연결 테스트 성공"
          schema:
            properties:
              test:
                type: string
        400:
          description: "Bad Request : 요청이 잘못되었습니다."
        404:
          description: "Not Found : 파일이 없습니다."
        500:
          description: "Unexpected Exception : 알 수 없는 에러입니다."

  /dog/createDog/{dogKey}:
    post:
      summary: "반려견을 등록합니다."
      description: "DB에 반려견을 등록합니다"
      tags:
        - dog
      parameters:
        - name: dogKey
          in: path
          type: string
          required: true

      responses:
        200:
          description: "등록한 반려견 정보를 내려줍니다"
          schema:
            properties:
              dogKey:
                type: string
        400:
          description: "Bad Request : 요청이 잘못되었습니다."
        403:
          description: "Forbidden : 권한이 없습니다."
        404:
          description: "Not Found : 파일이 없습니다."
        500:
          description: "Unexpected Exception : 알 수 없는 에러입니다."

  /dog/getDog/{dogKey}:
    get:
      summary: "반려견 정보를 받아옵니다."
      description: "DB에 저장된 반려견 정보를 받아옵니다"
      tags:
        - dog
      parameters:
        - name: dogKey
          in: path
          type: string
          required: true

      responses:
        200:
          description: "등록된 반려견 정보를 내려줍니다"
          schema:
            properties:
              dogKey:
                type: string
        400:
          description: "Bad Request : 요청이 잘못되었습니다."
        403:
          description: "Forbidden : 권한이 없습니다."
        404:
          description: "Not Found : 파일이 없습니다."
        500:
          description: "Unexpected Exception : 알 수 없는 에러입니다."

  /dog/addDogCrying/{dogKey}:
    post:
      summary: "반려견 울음을 카운트합니다."
      description: "DB에 울음 정보를 업로드합니다"
      tags:
        - dog
      parameters:
        - name: dogKey
          in: path
          type: string
          required: true
        - name: soundKey
          in: query
          type: string
          required: true
        - name: type
          in: query
          type: string
          required: true

      responses:
        200:
          description: "업로드한 울음 정보를 내려줍니다"
          schema:
            properties:
              dogKey:
                type: string
        400:
          description: "Bad Request : 요청이 잘못되었습니다."
        403:
          description: "Forbidden : 권한이 없습니다."
        404:
          description: "Not Found : 파일이 없습니다."
        500:
          description: "Unexpected Exception : 알 수 없는 에러입니다."

  /dog/getAllDogCrying/{dogKey}:
    get:
      summary: "반려견의 울음 정보를 가져옵니다."
      description: "DB에 저장된 울음 정보를 가져옵니다"
      tags:
        - dog
      parameters:
        - name: dogKey
          in: path
          type: string
          required: true

      responses:
        200:
          description: "저장된 울음 정보를 내려줍니다"
          schema:
            properties:
              sound:
                type: string
        400:
          description: "Bad Request : 요청이 잘못되었습니다."
        403:
          description: "Forbidden : 권한이 없습니다."
        404:
          description: "Not Found : 파일이 없습니다."
        500:
          description: "Unexpected Exception : 알 수 없는 에러입니다."
